export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
