export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';

export const GET_PRODUCT_ATTRIBUTES = 'GET_PRODUCT_ATTRIBUTES';
export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS';

export const MODAL_DIALOG = 'MODAL_DIALOG';
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';

export const ADD_CART_ITEM = 'ADD_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const CHECKOUT_CART = 'CHECKOUT_CART';
