export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';

export const GET_PRODUCT_ATTRIBUTES = 'GET_PRODUCT_ATTRIBUTES';
export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS';
